//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatCaster.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatCaster.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatCaster.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическое сохранение при изменении.
        /// </summary>
        internal static string Audio_AutoSave {
            get {
                return ResourceManager.GetString("Audio_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки.
        /// </summary>
        internal static string Audio_DownloadError {
            get {
                return ResourceManager.GetString("Audio_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        internal static string Audio_Language {
            get {
                return ResourceManager.GetString("Audio_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные настройки.
        /// </summary>
        internal static string Audio_MainSettings {
            get {
                return ResourceManager.GetString("Audio_MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Микрофон:.
        /// </summary>
        internal static string Audio_Microphone {
            get {
                return ResourceManager.GetString("Audio_Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терпимо, как борщ с пряником.
        /// </summary>
        internal static string Audio_Model_Base_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Base_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УльтраМозг, но съест всю твою оперативку.
        /// </summary>
        internal static string Audio_Model_Large_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Large_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarely makes mistakes, like a mathematician.
        /// </summary>
        internal static string Audio_Model_Medium_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Medium_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже сильно лучше, косяки редкие.
        /// </summary>
        internal static string Audio_Model_Small_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Small_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мгновенно, но тупой.
        /// </summary>
        internal static string Audio_Model_Tiny_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Tiny_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная модель.
        /// </summary>
        internal static string Audio_Model_Unknown {
            get {
                return ResourceManager.GetString("Audio_Model_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка проверки.
        /// </summary>
        internal static string Audio_ModelError {
            get {
                return ResourceManager.GetString("Audio_ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель не загружена.
        /// </summary>
        internal static string Audio_ModelNotLoaded {
            get {
                return ResourceManager.GetString("Audio_ModelNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель готова.
        /// </summary>
        internal static string Audio_ModelReady {
            get {
                return ResourceManager.GetString("Audio_ModelReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка микрофона, модели Whisper и параметров записи.
        /// </summary>
        internal static string Audio_PageDescription {
            get {
                return ResourceManager.GetString("Audio_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио и распознавание.
        /// </summary>
        internal static string Audio_PageTitle {
            get {
                return ResourceManager.GetString("Audio_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность записи:.
        /// </summary>
        internal static string Audio_RecordingDuration {
            get {
                return ResourceManager.GetString("Audio_RecordingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель Whisper:.
        /// </summary>
        internal static string Audio_WhisperModel {
            get {
                return ResourceManager.GetString("Audio_WhisperModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка....
        /// </summary>
        internal static string ButtonProcessing {
            get {
                return ResourceManager.GetString("ButtonProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записать.
        /// </summary>
        internal static string ButtonRecord {
            get {
                return ResourceManager.GetString("ButtonRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        internal static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Геймпад:.
        /// </summary>
        internal static string Control_Gamepad {
            get {
                return ResourceManager.GetString("Control_Gamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клавиатура:.
        /// </summary>
        internal static string Control_Keyboard {
            get {
                return ResourceManager.GetString("Control_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кликните на поле комбинации и нажмите нужные кнопки.
        /// </summary>
        internal static string Control_PageDescription {
            get {
                return ResourceManager.GetString("Control_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        internal static string Control_PageTitle {
            get {
                return ResourceManager.GetString("Control_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка записи.
        /// </summary>
        internal static string ErrorRecording {
            get {
                return ResourceManager.GetString("ErrorRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при обработке хоткея.
        /// </summary>
        internal static string HotkeyError {
            get {
                return ResourceManager.GetString("HotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кнопка закрытия (X) сворачивает в трей.
        /// </summary>
        internal static string Interface_MinimizeToTray {
            get {
                return ResourceManager.GetString("Interface_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay индикатор.
        /// </summary>
        internal static string Interface_OverlayIndicator {
            get {
                return ResourceManager.GetString("Interface_OverlayIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка overlay индикатора и системных параметров.
        /// </summary>
        internal static string Interface_PageDescription {
            get {
                return ResourceManager.GetString("Interface_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интерфейс.
        /// </summary>
        internal static string Interface_PageTitle {
            get {
                return ResourceManager.GetString("Interface_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция:.
        /// </summary>
        internal static string Interface_Position {
            get {
                return ResourceManager.GetString("Interface_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижний центр.
        /// </summary>
        internal static string Interface_Position_BottomCenter {
            get {
                return ResourceManager.GetString("Interface_Position_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижний левый.
        /// </summary>
        internal static string Interface_Position_BottomLeft {
            get {
                return ResourceManager.GetString("Interface_Position_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижний правый.
        /// </summary>
        internal static string Interface_Position_BottomRight {
            get {
                return ResourceManager.GetString("Interface_Position_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр.
        /// </summary>
        internal static string Interface_Position_MiddleCenter {
            get {
                return ResourceManager.GetString("Interface_Position_MiddleCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний левый.
        /// </summary>
        internal static string Interface_Position_MiddleLeft {
            get {
                return ResourceManager.GetString("Interface_Position_MiddleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний правый.
        /// </summary>
        internal static string Interface_Position_MiddleRight {
            get {
                return ResourceManager.GetString("Interface_Position_MiddleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхний центр.
        /// </summary>
        internal static string Interface_Position_TopCenter {
            get {
                return ResourceManager.GetString("Interface_Position_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхний левый.
        /// </summary>
        internal static string Interface_Position_TopLeft {
            get {
                return ResourceManager.GetString("Interface_Position_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхний правый.
        /// </summary>
        internal static string Interface_Position_TopRight {
            get {
                return ResourceManager.GetString("Interface_Position_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать уведомления.
        /// </summary>
        internal static string Interface_ShowNotifications {
            get {
                return ResourceManager.GetString("Interface_ShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать overlay во время записи.
        /// </summary>
        internal static string Interface_ShowOverlay {
            get {
                return ResourceManager.GetString("Interface_ShowOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускать свернутым в трей.
        /// </summary>
        internal static string Interface_StartMinimized {
            get {
                return ResourceManager.GetString("Interface_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускать с Windows.
        /// </summary>
        internal static string Interface_StartWithWindows {
            get {
                return ResourceManager.GetString("Interface_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимость:.
        /// </summary>
        internal static string Interface_Visibility {
            get {
                return ResourceManager.GetString("Interface_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        internal static string LanguageName_en_US {
            get {
                return ResourceManager.GetString("LanguageName_en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string LanguageName_ru_RU {
            get {
                return ResourceManager.GetString("LanguageName_ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точность: высокая.
        /// </summary>
        internal static string Main_ConfidenceHigh {
            get {
                return ResourceManager.GetString("Main_ConfidenceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Микрофон не выбран.
        /// </summary>
        internal static string Main_CurrentDevice {
            get {
                return ResourceManager.GetString("Main_CurrentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний результат.
        /// </summary>
        internal static string Main_LastResult {
            get {
                return ResourceManager.GetString("Main_LastResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здесь появится распознанный текст....
        /// </summary>
        internal static string Main_PlaceholderText {
            get {
                return ResourceManager.GetString("Main_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время: &amp;lt; 1с.
        /// </summary>
        internal static string Main_ProcessingTimeFast {
            get {
                return ResourceManager.GetString("Main_ProcessingTimeFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось распознать речь.
        /// </summary>
        internal static string Main_RecognitionFailed {
            get {
                return ResourceManager.GetString("Main_RecognitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навигация.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио и распознавание.
        /// </summary>
        internal static string Navigation_Audio {
            get {
                return ResourceManager.GetString("Navigation_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        internal static string Navigation_Control {
            get {
                return ResourceManager.GetString("Navigation_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интерфейс.
        /// </summary>
        internal static string Navigation_Interface {
            get {
                return ResourceManager.GetString("Navigation_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главное.
        /// </summary>
        internal static string Navigation_Main {
            get {
                return ResourceManager.GetString("Navigation_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка.
        /// </summary>
        internal static string StatusProcessing {
            get {
                return ResourceManager.GetString("StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готов к записи.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись.
        /// </summary>
        internal static string StatusRecording {
            get {
                return ResourceManager.GetString("StatusRecording", resourceCulture);
            }
        }
    }
}
