//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatCaster.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatCaster.Core.Resources.Strings.en-US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatCaster.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-save on change.
        /// </summary>
        internal static string Audio_AutoSave {
            get {
                return ResourceManager.GetString("Audio_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error.
        /// </summary>
        internal static string Audio_DownloadError {
            get {
                return ResourceManager.GetString("Audio_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Audio_Language {
            get {
                return ResourceManager.GetString("Audio_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Settings.
        /// </summary>
        internal static string Audio_MainSettings {
            get {
                return ResourceManager.GetString("Audio_MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone:.
        /// </summary>
        internal static string Audio_Microphone {
            get {
                return ResourceManager.GetString("Audio_Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decent enough, like pizza with pineapple.
        /// </summary>
        internal static string Audio_Model_Base_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Base_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraBrain, but will eat all your RAM.
        /// </summary>
        internal static string Audio_Model_Large_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Large_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почти не ошибается, как математик.
        /// </summary>
        internal static string Audio_Model_Medium_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Medium_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Much better, mistakes are rare.
        /// </summary>
        internal static string Audio_Model_Small_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Small_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning fast, but dumb as rocks.
        /// </summary>
        internal static string Audio_Model_Tiny_Desc {
            get {
                return ResourceManager.GetString("Audio_Model_Tiny_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown model.
        /// </summary>
        internal static string Audio_Model_Unknown {
            get {
                return ResourceManager.GetString("Audio_Model_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check error.
        /// </summary>
        internal static string Audio_ModelError {
            get {
                return ResourceManager.GetString("Audio_ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model not loaded.
        /// </summary>
        internal static string Audio_ModelNotLoaded {
            get {
                return ResourceManager.GetString("Audio_ModelNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ready.
        /// </summary>
        internal static string Audio_ModelReady {
            get {
                return ResourceManager.GetString("Audio_ModelReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone, Whisper model and recording settings.
        /// </summary>
        internal static string Audio_PageDescription {
            get {
                return ResourceManager.GetString("Audio_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio &amp; Recognition.
        /// </summary>
        internal static string Audio_PageTitle {
            get {
                return ResourceManager.GetString("Audio_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Duration:.
        /// </summary>
        internal static string Audio_RecordingDuration {
            get {
                return ResourceManager.GetString("Audio_RecordingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper Model:.
        /// </summary>
        internal static string Audio_WhisperModel {
            get {
                return ResourceManager.GetString("Audio_WhisperModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string ButtonProcessing {
            get {
                return ResourceManager.GetString("ButtonProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string ButtonRecord {
            get {
                return ResourceManager.GetString("ButtonRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad:.
        /// </summary>
        internal static string Control_Gamepad {
            get {
                return ResourceManager.GetString("Control_Gamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard:.
        /// </summary>
        internal static string Control_Keyboard {
            get {
                return ResourceManager.GetString("Control_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on combination field and press desired buttons.
        /// </summary>
        internal static string Control_PageDescription {
            get {
                return ResourceManager.GetString("Control_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Control_PageTitle {
            get {
                return ResourceManager.GetString("Control_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording error.
        /// </summary>
        internal static string ErrorRecording {
            get {
                return ResourceManager.GetString("ErrorRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing hotkey.
        /// </summary>
        internal static string HotkeyError {
            get {
                return ResourceManager.GetString("HotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close button (X) minimizes to tray.
        /// </summary>
        internal static string Interface_MinimizeToTray {
            get {
                return ResourceManager.GetString("Interface_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Indicator.
        /// </summary>
        internal static string Interface_OverlayIndicator {
            get {
                return ResourceManager.GetString("Interface_OverlayIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay indicator and system settings.
        /// </summary>
        internal static string Interface_PageDescription {
            get {
                return ResourceManager.GetString("Interface_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string Interface_PageTitle {
            get {
                return ResourceManager.GetString("Interface_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        internal static string Interface_Position {
            get {
                return ResourceManager.GetString("Interface_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        internal static string Interface_Position_BottomCenter {
            get {
                return ResourceManager.GetString("Interface_Position_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string Interface_Position_BottomLeft {
            get {
                return ResourceManager.GetString("Interface_Position_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string Interface_Position_BottomRight {
            get {
                return ResourceManager.GetString("Interface_Position_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Interface_Position_MiddleCenter {
            get {
                return ResourceManager.GetString("Interface_Position_MiddleCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Left.
        /// </summary>
        internal static string Interface_Position_MiddleLeft {
            get {
                return ResourceManager.GetString("Interface_Position_MiddleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Right.
        /// </summary>
        internal static string Interface_Position_MiddleRight {
            get {
                return ResourceManager.GetString("Interface_Position_MiddleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        internal static string Interface_Position_TopCenter {
            get {
                return ResourceManager.GetString("Interface_Position_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string Interface_Position_TopLeft {
            get {
                return ResourceManager.GetString("Interface_Position_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string Interface_Position_TopRight {
            get {
                return ResourceManager.GetString("Interface_Position_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notifications.
        /// </summary>
        internal static string Interface_ShowNotifications {
            get {
                return ResourceManager.GetString("Interface_ShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show overlay during recording.
        /// </summary>
        internal static string Interface_ShowOverlay {
            get {
                return ResourceManager.GetString("Interface_ShowOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized to tray.
        /// </summary>
        internal static string Interface_StartMinimized {
            get {
                return ResourceManager.GetString("Interface_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        internal static string Interface_StartWithWindows {
            get {
                return ResourceManager.GetString("Interface_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility:.
        /// </summary>
        internal static string Interface_Visibility {
            get {
                return ResourceManager.GetString("Interface_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageName_en_US {
            get {
                return ResourceManager.GetString("LanguageName_en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LanguageName_ru_RU {
            get {
                return ResourceManager.GetString("LanguageName_ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence: high.
        /// </summary>
        internal static string Main_ConfidenceHigh {
            get {
                return ResourceManager.GetString("Main_ConfidenceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No microphone selected.
        /// </summary>
        internal static string Main_CurrentDevice {
            get {
                return ResourceManager.GetString("Main_CurrentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Result.
        /// </summary>
        internal static string Main_LastResult {
            get {
                return ResourceManager.GetString("Main_LastResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition result will appear here....
        /// </summary>
        internal static string Main_PlaceholderText {
            get {
                return ResourceManager.GetString("Main_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: &amp;lt; 1s.
        /// </summary>
        internal static string Main_ProcessingTimeFast {
            get {
                return ResourceManager.GetString("Main_ProcessingTimeFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognition failed.
        /// </summary>
        internal static string Main_RecognitionFailed {
            get {
                return ResourceManager.GetString("Main_RecognitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio &amp; Recognition.
        /// </summary>
        internal static string Navigation_Audio {
            get {
                return ResourceManager.GetString("Navigation_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Navigation_Control {
            get {
                return ResourceManager.GetString("Navigation_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string Navigation_Interface {
            get {
                return ResourceManager.GetString("Navigation_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Navigation_Main {
            get {
                return ResourceManager.GetString("Navigation_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string StatusProcessing {
            get {
                return ResourceManager.GetString("StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to record.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string StatusRecording {
            get {
                return ResourceManager.GetString("StatusRecording", resourceCulture);
            }
        }
    }
}
