//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatCaster.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatCaster.Core.Resources.Strings.en-US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatCaster.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-save on change.
        /// </summary>
        internal static string Audio_AutoSave {
            get {
                return ResourceManager.GetString("Audio_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Audio_Language {
            get {
                return ResourceManager.GetString("Audio_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Settings.
        /// </summary>
        internal static string Audio_MainSettings {
            get {
                return ResourceManager.GetString("Audio_MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone:.
        /// </summary>
        internal static string Audio_Microphone {
            get {
                return ResourceManager.GetString("Audio_Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone, Whisper model and recording settings.
        /// </summary>
        internal static string Audio_PageDescription {
            get {
                return ResourceManager.GetString("Audio_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio &amp; Recognition.
        /// </summary>
        internal static string Audio_PageTitle {
            get {
                return ResourceManager.GetString("Audio_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Duration:.
        /// </summary>
        internal static string Audio_RecordingDuration {
            get {
                return ResourceManager.GetString("Audio_RecordingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper Model:.
        /// </summary>
        internal static string Audio_WhisperModel {
            get {
                return ResourceManager.GetString("Audio_WhisperModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording error.
        /// </summary>
        internal static string ErrorRecording {
            get {
                return ResourceManager.GetString("ErrorRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing hotkey.
        /// </summary>
        internal static string HotkeyError {
            get {
                return ResourceManager.GetString("HotkeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageName_en_US {
            get {
                return ResourceManager.GetString("LanguageName_en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LanguageName_ru_RU {
            get {
                return ResourceManager.GetString("LanguageName_ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio &amp; Recognition.
        /// </summary>
        internal static string Navigation_Audio {
            get {
                return ResourceManager.GetString("Navigation_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Navigation_Control {
            get {
                return ResourceManager.GetString("Navigation_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string Navigation_Interface {
            get {
                return ResourceManager.GetString("Navigation_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Navigation_Main {
            get {
                return ResourceManager.GetString("Navigation_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string StatusProcessing {
            get {
                return ResourceManager.GetString("StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string StatusRecording {
            get {
                return ResourceManager.GetString("StatusRecording", resourceCulture);
            }
        }
    }
}
